services:
  - type: web
    name: upc-finder
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: UPC_API_KEY
        sync: false
    healthCheckPath: /